#include "httpstatuscode.h"

const QLatin1StringView HttpStatusCode::toString(Code code)
{
    static const std::unordered_map<Code, QLatin1StringView> map{
#define XX(name, string) {Code::name, QLatin1StringView(string)}
        XX(Continue, "Continue"),
        XX(SwitchingProtocols, "Switching Protocols"),
        XX(Processing, "Processing"),
        XX(Ok, "OK"),
        XX(Created, "Created"),
        XX(Accepted, "Accepted"),
        XX(NonAuthoritativeInformation, "Non-Authoritative Information"),
        XX(NoContent, "No Content"),
        XX(ResetContent, "Reset Content"),
        XX(PartialContent, "Partial Content"),
        XX(MultiStatus, "Multi-Status"),
        XX(AlreadyReported, "Already Reported"),
        XX(IMUsed, "I'm Used"),
        XX(MultipleChoices, "Multiple Choices"),
        XX(MovedPermanently, "Moved Permanently"),
        XX(Found, "Found"),
        XX(SeeOther, "See Other"),
        XX(NotModified, "Not Modified"),
        XX(UseProxy, "Use Proxy"),
        XX(TemporaryRedirect, "Temporary Redirect"),
        XX(PermanentRedirect, "Permanent Redirect"),
        XX(BadRequest, "Bad Request"),
        XX(Unauthorized, "Unauthorized"),
        XX(PaymentRequired, "Payment Required"),
        XX(Forbidden, "Forbidden"),
        XX(NotFound, "Not Found"),
        XX(MethodNotAllowed, "Method Not Allowed"),
        XX(NotAcceptable, "Not Acceptable"),
        XX(ProxyAuthenticationRequired, "Proxy Authentication Required"),
        XX(RequestTimeout, "Request Timeout"),
        XX(Conflict, "Conflict"),
        XX(Gone, "Gone"),
        XX(LengthRequired, "Length Required"),
        XX(PreconditionFailed, "Precondition Failed"),
        XX(PayloadTooLarge, "Request Entity Too Large"),
        XX(UriTooLong, "Request-URI Too Long"),
        XX(UnsupportedMediaType, "Unsupported Media Type"),
        XX(RequestRangeNotSatisfiable, "Requested Range Not Satisfiable"),
        XX(ExpectationFailed, "Expectation Failed"),
        XX(ImATeapot, "I'm a teapot"),
        XX(MisdirectedRequest, "Misdirected Request"),
        XX(UnprocessableEntity, "Unprocessable Entity"),
        XX(Locked, "Locked"),
        XX(FailedDependency, "Failed Dependency"),
        XX(UpgradeRequired, "Upgrade Required"),
        XX(PreconditionRequired, "Precondition Required"),
        XX(TooManyRequests, "Too Many Requests"),
        XX(RequestHeaderFieldsTooLarge, "Request Header Fields Too Large"),
        XX(UnavailableForLegalReasons, "Unavailable For Legal Reasons"),
        XX(InternalServerError, "Internal Server Error"),
        XX(NotImplemented, "Not Implemented"),
        XX(BadGateway, "Bad Gateway"),
        XX(ServiceUnavailable, "Service Unavailable"),
        XX(GatewayTimeout, "Gateway Timeout"),
        XX(HttpVersionNotSupported, "HTTP Version Not Supported"),
        XX(VariantAlsoNegotiates, "Variant Also Negotiates"),
        XX(InsufficientStorage, "Insufficient Storage"),
        XX(LoopDetected, "Loop Detected"),
        XX(NotExtended, "Not Extended"),
        XX(NetworkAuthenticationRequired, "Network Authentication Required"),
        XX(NetworkConnectTimeoutError, "Network Connect Timeout Error"),
#undef XX
    };
    return map.contains(code) ? map.at(code) : QLatin1StringView("Unknown Status Code");
}
