#ifndef _CLIENTMODELS_ROOMMEMBERSHIPROLE_H_CUSTOM
#define _CLIENTMODELS_ROOMMEMBERSHIPROLE_H_CUSTOM

#ifdef _MSC_VER
#pragma once
#endif

/* -- Put your custom code here -- */

#endif // _CLIENTMODELS_ROOMMEMBERSHIPROLE_H_CUSTOM
